gitlab:
  url: https://gitlab.example.com
  token: abcdef1234567890
slack:
  webhook_url: https://hooks.slack.com/services/your-slack-webhook-url
projects:
  - id: 123
  - id: 456
groups:
  - id: 1
  - id: 2
